### ISSUE TITLE
WARN deprecated @npmcli/move-file & The `punycode` module is deprecated

### ISSUE THREAD

**Issue by mhuch** [atlowChemi/vite-svg-2-webfont#17]
Hello.

First, if i install the package i get 
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

And then, on npm run dev, i got this Warning.
(node:10051) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

My Setup:
Node.js v21.6.1.
Vite v5.0.8

**Comment by atlowChemi** [comment]
The issue was with a dependency which has been outdated (specifically an issue with [cacache fixed here](https://github.com/npm/cacache/blob/main/CHANGELOG.md#1702-2022-11-04))

I am opening a PR that should resolve this, thank you for reporting!
