### ISSUE TITLE
SCSS-Template support?

### ISSUE THREAD

**Issue by docmg** [atlowChemi/vite-svg-2-webfont#27]
Hey.
Thank you for such wonderful plugin.

**I have the following questions:**
- Is it possible somehow to use custom scssTemplate? In configuration sadly is only possible to override cssTemplate.
- Is it possible to import virtual module in scss files? The example in readme is only for js/ts.
- How can i use the webfont-icon mixin if it is not possible to import scss file generated by the plugin?

Sorry for the questions, i dont have much experience with vite and im currently trying to migrate from gulp.

PS. Im trying to use your plugin as an replacement for [gulp-iconfont](https://www.npmjs.com/package/gulp-iconfont).

**Comment by atlowChemi** [comment]
> Is it possible somehow to use custom scssTemplate? In configuration sadly is only possible to override cssTemplate.

You can pass a `.scss` template to the `cssTemplate` field, and change the `cssDest` to a file ending with `.scss`  🙂 
See the SCSS template of `@vusion/webfonts-generator` [here](https://github.com/vusion/webfonts-generator/blob/master/templates/scss.hbs)


> Is it possible to import virtual module in scss files? The example in readme is only for js/ts.

I am honestly not sure regarding this, but you could give it a try, would be great to document it if it works! 🤩 

> How can i use the webfont-icon mixin if it is not possible to import scss file generated by the plugin?

Again - have a look at the `@vusion/webfonts-generator` template which uses it 🚀 


> Sorry for the questions, i dont have much experience with vite and im currently trying to migrate from gulp.
> PS. Im trying to use your plugin as an replacement for [gulp-iconfont](https://www.npmjs.com/package/gulp-iconfont).

Don't be sorry, I hope this tool could be useful 😄

**Comment by atlowChemi** [comment]
I'll be closing this issue, if you feel there is any further questions, or if you wish to open a PR clarifying the documentation - feel free to reopen 🙂
